---
version: "3.7"

services:
  ocis:
    image: owncloud/ocis:latest
    depends_on:
      - ldap-server
    environment:
      PROXY_CONFIG_FILE: "/config/proxy-config.json"
      LDAP_FILTER: "(&(objectclass=inetOrgPerson)(objectClass=owncloud))"
      LDAP_URI: ldap://ldap-server:389
      LDAP_BINDDN: "cn=admin,dc=owncloud,dc=com"
      LDAP_BINDPW: admin
      LDAP_BASEDN: "dc=owncloud,dc=com"
      LDAP_LOGIN_ATTRIBUTE: uid
      LDAP_UUID_ATTRIBUTE: "ownclouduuid"
      LDAP_UUID_ATTRIBUTE_TYPE: binary
      PROXY_ACCOUNT_BACKEND_TYPE: cs3
      STORAGE_LDAP_HOSTNAME: ldap-server
      STORAGE_LDAP_PORT: 636
      STORAGE_LDAP_BASE_DN: "dc=owncloud,dc=com"
      STORAGE_LDAP_BIND_DN: "cn=admin,dc=owncloud,dc=com"
      STORAGE_LDAP_BIND_PASSWORD: admin
      STORAGE_LDAP_LOGINFILTER: '(&(objectclass=inetOrgPerson)(objectclass=owncloud)(|(uid={{login}})(mail={{login}})))'
      STORAGE_LDAP_USERFILTER: '(&(objectclass=inetOrgPerson)(objectclass=owncloud)(|(ownclouduuid={{.OpaqueId}})(uid={{.OpaqueId}})))'
      STORAGE_LDAP_ATTRIBUTEFILTER: '(&(objectclass=owncloud)({{attr}}={{value}}))'
      STORAGE_LDAP_FINDFILTER: '(&(objectclass=owncloud)(|(uid={{query}}*)(cn={{query}}*)(displayname={{query}}*)(mail={{query}}*)(description={{query}}*)))'
      STORAGE_LDAP_GROUPFILTER: '(&(objectclass=groupOfUniqueNames)(objectclass=owncloud)(ownclouduuid={{.OpaqueId}}*))'
    ports:
      - "9200:9200"
    volumes:
      - ./ocis/config/proxy-config.json:/config/proxy-config.json

  ldap-server:
    image: osixia/openldap:latest
    command: --copy-service --loglevel debug
    environment:
      LDAP_TLS_VERIFY_CLIENT: never
      LDAP_DOMAIN: owncloud.com
      LDAP_ORGANISATION: ownCloud
      LDAP_ADMIN_PASSWORD: admin
      LDAP_RFC2307BIS_SCHEMA: "true"
      LDAP_REMOVE_CONFIG_AFTER_SETUP: "false"
    ports:
      - "389:389"
      - "636:636"
    volumes:
      - ./ldap/ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom

